name: ViaBackwards
version: ${project.version}
description: Allow older Minecraft versions to connect to a newer server version.
main: nl.matsv.viabackwards.BukkitPlugin

authors: [Matsv]
website: https://matsv.nl

load: STARTUP
depend: [ViaVersion]
